version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "rut"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mysql-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-network

networks: 
  mysql-network:
    driver: bridge